// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arnengxblsfnezrqcsxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybmVuZ3hibHNmbmV6cnFjc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTc2MjIsImV4cCI6MjA1NDA5MzYyMn0.OypUeuu_zFPeXH97jI-wbosEM6EtTsKqEaQapjYGSpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);