
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY } from '@/config/env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Environment variables are validated in @/config/env.ts
// App will fail fast at startup if required variables are missing
export const supabase = createClient<Database>(
  VITE_SUPABASE_URL,
  VITE_SUPABASE_ANON_KEY
);
